# Generated by Django 6.0.7 on 2026-08-13 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_category_favoritearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='comments/media/'),
        ),
    ]
