# Generated by Django 6.0.7 on 2026-08-13 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_comment_media_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('media', 'Media')], max_length=10)),
                ('content', models.TextField(blank=True)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='articles/blocks/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='articles.article')),
            ],
            options={
                'verbose_name': 'Article Block',
                'verbose_name_plural': 'Article Blocks',
                'ordering': ['order', 'id'],
            },
        ),
    ]
