# Generated by Django 6.0.7 on 2026-08-18 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_article_to_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='accepted_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for', to='articles.comment'),
        ),
    ]
