# Generated by Django 6.0.7 on 2026-08-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_question_accepted_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='forum/questions/'),
        ),
    ]
