# Generated by Django 6.0.7 on 2026-08-18 09:51

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension

class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_cover_rating'),
    ]

    operations = [
        TrigramExtension(),
    ]
