# Generated by Django 6.0.7 on 2026-08-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_section_contentblock_delete_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('video_link', 'Video link'), ('link', 'Link'), ('media', 'Media')], default='text', max_length=20),
        ),
    ]
