# Generated by Django 6.0.7 on 2026-08-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_section_contentblock_delete_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('media', 'Media'), ('video_link', 'Video link')], default='text', max_length=20),
        ),
    ]
