# Generated by Django 6.0.7 on 2026-08-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_contentblock_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('media', 'Media'), ('video_link', 'Video link'), ('document_link', 'Document link')], default='text', max_length=20),
        ),
    ]
