# Generated by Django 6.0.7 on 2026-08-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_category_code_category_description_resource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('document', 'Document'), ('image', 'Image'), ('notes', 'Lecture notes'), ('cheatsheet', 'Cheat sheet'), ('past_paper', 'Past paper'), ('link', 'Link'), ('video', 'Video')], max_length=20),
        ),
    ]
