# Generated by Django 6.0.7 on 2026-08-13 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_article_cover_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='media_file',
        ),
    ]
