# Generated by hand: Article -> Question forum rewrite.
#
# ArticleBlock is dropped (Question has no rich-content blocks, just a text
# body), Article becomes Question, and the FKs that pointed at it (Comment,
# FavoriteArticle) are renamed to match — done as RenameModel/RenameField so
# existing rows survive instead of a drop-and-recreate.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_remove_article_media_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleblock',
            name='article',
        ),
        migrations.DeleteModel(
            name='ArticleBlock',
        ),
        migrations.RenameModel(
            old_name='Article',
            new_name='Question',
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='question',
            name='published_at',
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='questions',
                to='courses.category',
            ),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='questions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='question',
        ),
        migrations.RemoveConstraint(
            model_name='favoritearticle',
            name='unique_user_article_favorite',
        ),
        migrations.RenameField(
            model_name='favoritearticle',
            old_name='article',
            new_name='question',
        ),
        migrations.AddConstraint(
            model_name='favoritearticle',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='unique_user_question_favorite'),
        ),
    ]
